apiVersion: 'v1'
kind: 'Secret'
type: 'Opaque'
metadata:
  name: '{{ .Release.Name }}'
  labels:
    app: '{{ .Release.Name }}'
    version: '{{ .Values.git.commitHash }}'
stringData:
  .env: |
    NEXTAUTH_URL=https://{{ .Values.ingress.url }}
    NEXTAUTH_SECRET={{ .Values.nextauth.secret }}

    KEYCLOAK_ISSUER={{ .Values.keycloak.issuer }}
    KEYCLOAK_CLIENT_ID={{ .Values.keycloak.clientId }}
    KEYCLOAK_CLIENT_SECRET={{ .Values.keycloak.clientSecret }}

    API_URL={{ .Values.api.url }}
    CADOK_URL={{ .Values.api.cadokUrl }}
    HELM_REPO={{ .Values.api.helmRepo }}

    NEXT_PUBLIC_SENTRY_DSN={{ .Values.sentry.dsn }}
    SENTRY_DSN={{ .Values.sentry.dsn }}

    STRAPI_API_URL={{ .Values.strapi.url }}
    STRAPI_API_TOKEN={{ .Values.strapi.apiToken }}
